# Generated by Django 4.2.8 on 2024-01-11 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ecomm_app", "0003_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="pid",
            field=models.ForeignKey(
                db_column="pid",
                on_delete=django.db.models.deletion.CASCADE,
                to="ecomm_app.product",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="uid",
            field=models.ForeignKey(
                db_column="uid",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
